"""Make guest unique per planner ONLY.

Revision ID: 976a60c67d77
Revises: dbea60466f08
Create Date: 2025-07-03 07:11:17.656407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976a60c67d77'
down_revision = 'dbea60466f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('guests_email_key'), type_='unique')
        batch_op.create_unique_constraint('_guest_email_planner_uc', ['email', 'planner_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint('_guest_email_planner_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('guests_email_key'), ['email'])

    # ### end Alembic commands ###
